[build]
  command = "CI=false npm install && npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  NETLIFY_SKIP_INIT_BUILD = "true"
  NETLIFY_SKIP_PLUGIN_SETUP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"