create table telegram_users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  username text,
  first_name text,
  last_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS policies
alter table telegram_users enable row level security;

create policy "Enable insert for authenticated users" on telegram_users
  for insert with check (true);

create policy "Enable select for authenticated users" on telegram_users
  for select using (true);

create policy "Enable update for authenticated users" on telegram_users
  for update using (true); 